version: '3.8'

services:
  api-gateway:
    build:
      context: .
      dockerfile: ApiGateway/Dockerfile
    ports:
      - "8080:80"
    depends_on:
      - payments-service
      - orders-service
    environment:
      - PaymentsServiceUrl=http://payments-service

  payments-service:
    build:
      context: .
      dockerfile: PaymentsService/Dockerfile
    expose:
      - "80"
  orders-service:
    build:
      context: .
      dockerfile: OrdersService/Dockerfile
    expose:
      - "80"

networks:
  default:
    driver: bridge