version: '3.8'

services:
  api-gateway:
    build:
      context: .
      dockerfile: ApiGateway/Dockerfile
    ports:
      - "8080:80"
    depends_on:
      - text-analysis
    environment:
      - TextAnalysisServiceUrl=http://text-analysis

  text-analysis:
    build:
      context: .
      dockerfile: TextAnalysisService/Dockerfile
    expose:
      - "80"

networks:
  default:
    driver: bridge